export const removedScopeTerms = [
  'admin approval',
  'pending registration',
  'rejected registration',
  'temporary password',
  'skill master',
  'verified skill',
  'estimated GPA planner',
  'CV review',
  'CV approval',
  'company login',
  'company portal',
  'AI ranking',
  'AI scoring',
  'match percentage',
  'automated selection',
  'project approval',
  'project verification',
  'GPA inside internship request',
  'GPA request field',
] as const
