export * from './AuthSkeleton'
export * from './DashboardSkeleton'
export * from './FormSkeleton'
export * from './TableSkeleton'
export * from './StudentSkillsSkeleton'
export * from './StudentProjectsSkeleton'
export * from './WorkspaceSkeleton'
