import { EmptyState } from '../../../shared/components/feedback/EmptyState'
import { ErrorState } from '../../../shared/components/feedback/ErrorState'
import { LoadingBoundary } from '../../../shared/components/feedback/LoadingBoundary'
import { SectionCard } from '../../../shared/components/layout/SectionCard'
import { CvPreviewPaperSkeleton } from '../../../shared/skeletons/CvBuilderSkeleton'
import type { CvPreview } from '../types/cvBuilderTypes'
import { sanitizeCvHtml } from '../utils/sanitizeCvHtml'

export function CvPreviewPanel({
  dirty,
  error,
  expired,
  isPending,
  onRetry,
  preview,
}: {
  preview: CvPreview | null
  dirty: boolean
  expired: boolean
  isPending: boolean
  error?: { message: string; correlationId?: string } | null
  onRetry: () => void
}) {
  return (
    <SectionCard aria-labelledby="cv-preview-title" className="s5-cv-preview-panel">
      <div className="s5-section-heading">
        <div>
          <h2 id="cv-preview-title">ATS-compliant CV preview</h2>
          <p>Review the isolated, read-only output generated by the CV service.</p>
        </div>
        {dirty && preview ? (
          <span className="s5-status-pill warning">Last generated preview</span>
        ) : null}
      </div>

      {dirty && preview ? (
        <p className="s5-inline-warning" role="status">
          Your controls changed after this preview. Choose Update Preview before saving.
        </p>
      ) : null}
      {expired && preview ? (
        <div className="s5-inline-alert" role="alert">
          <strong>This preview has expired.</strong>
          <span>Your configuration is preserved. Regenerate the preview before saving.</span>
        </div>
      ) : null}
      <LoadingBoundary
        isLoading={isPending}
        label="Generating CV preview"
        minHeight={680}
        skeleton={<CvPreviewPaperSkeleton />}
      >
        {error ? (
          <ErrorState
            correlationId={error.correlationId}
            message={error.message}
            onAction={onRetry}
            title="Preview generation failed"
          />
        ) : preview ? (
          <div className="s5-cv-preview-paper">
            <iframe
              className="s5-cv-preview-frame"
              referrerPolicy="no-referrer"
              sandbox=""
              srcDoc={buildPreviewDocument(preview.htmlPreview)}
              tabIndex={-1}
              title="Generated CV visual preview"
            />
          </div>
        ) : (
          <EmptyState
            message="Choose the records to include, then generate an explicit preview."
            title="No preview generated"
          />
        )}
      </LoadingBoundary>
    </SectionCard>
  )
}

const previewStyles = `
html{background:#eef0f3;color:#1c1c1c;font:14px/1.55 'Liberation Sans',Arial,Helvetica,sans-serif}
body{margin:0;padding:40px 20px}
.cv-document{max-width:760px;margin:0 auto;background:#fff;padding:48px 56px;border:1px solid #e2e2e2;box-shadow:0 1px 4px rgba(0,0,0,.08)}
.cv-header{text-align:center;margin-bottom:18px;padding-bottom:14px;border-bottom:2px solid #1c385e}
.cv-header h1{font-size:30px;margin:0 0 6px;letter-spacing:.4px}
.cv-headline{font-style:italic;color:#444;margin:0 0 8px;font-size:14px}
.cv-contact,.cv-links{margin:2px 0;font-size:12.5px;color:#333}
.cv-links a{color:#1c385e;text-decoration:underline}
section{margin-top:20px}
section:first-of-type{margin-top:0}
section>h2{font-size:13px;letter-spacing:1px;text-transform:uppercase;font-weight:700;color:#1c385e;margin:0 0 8px;padding-bottom:4px;border-bottom:1px solid #1c385e}
article{margin-bottom:14px}
article:last-child{margin-bottom:0}
article>h3{font-size:14.5px;margin:0;font-weight:700}
.cv-meta{margin:2px 0 6px;font-size:12.5px;font-style:italic;color:#555}
p{margin:4px 0;font-size:13.5px}
ul{margin:6px 0;padding-left:20px}
li{margin:3px 0;font-size:13.5px}
a{color:#1c385e;text-decoration:none;border-bottom:1px solid #ccc}
strong{font-weight:700}
`.replace(/\n/g, '')

export function buildPreviewDocument(htmlPreview: string) {
  const sanitizedPreview = sanitizeCvHtml(htmlPreview)
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src 'none'; connect-src 'none'; frame-src 'none'; form-action 'none'; base-uri 'none';"><meta name="referrer" content="no-referrer"><style>${previewStyles}</style></head><body>${sanitizedPreview}</body></html>`
}
