import { EmptyState } from '../../../shared/components/feedback/EmptyState'
import { ErrorState } from '../../../shared/components/feedback/ErrorState'
import { SkeletonBlock } from '../../../shared/components/feedback/SkeletonBlock'
import { SectionCard } from '../../../shared/components/layout/SectionCard'
import type { CvPreview } from '../types/cvBuilderTypes'
import { sanitizeCvHtml } from '../utils/sanitizeCvHtml'

export function CvPreviewPanel({
  dirty,
  error,
  expired,
  isPending,
  onRetry,
  preview,
}: {
  preview: CvPreview | null
  dirty: boolean
  expired: boolean
  isPending: boolean
  error?: { message: string; correlationId?: string } | null
  onRetry: () => void
}) {
  return (
    <SectionCard aria-labelledby="cv-preview-title" className="s5-cv-preview-panel">
      <div className="s5-section-heading">
        <div>
          <h2 id="cv-preview-title">Visual ATS preview</h2>
          <p>Isolated, read-only output generated by the CV service.</p>
        </div>
        {dirty && preview ? (
          <span className="s5-status-pill warning">Last generated preview</span>
        ) : null}
      </div>

      {dirty && preview ? (
        <p className="s5-inline-warning" role="status">
          Your controls changed after this preview. Choose Update Preview before saving.
        </p>
      ) : null}
      {expired && preview ? (
        <div className="s5-inline-alert" role="alert">
          <strong>This preview has expired.</strong>
          <span>Your configuration is preserved. Regenerate the preview before saving.</span>
        </div>
      ) : null}
      {isPending ? (
        <div aria-label="Generating CV preview" className="s5-cv-preview-loading" role="status">
          <span className="visually-hidden">Generating CV preview</span>
          <SkeletonBlock lines={8} />
        </div>
      ) : null}
      {error ? (
        <ErrorState
          correlationId={error.correlationId}
          message={error.message}
          onAction={onRetry}
          title="Preview generation failed"
        />
      ) : null}
      {!preview && !isPending && !error ? (
        <EmptyState
          message="Choose your sections and projects, then generate an explicit preview."
          title="No preview generated"
        />
      ) : null}
      {preview ? (
        <div className="s5-cv-preview-paper">
          <iframe
            className="s5-cv-preview-frame"
            referrerPolicy="no-referrer"
            sandbox=""
            srcDoc={buildPreviewDocument(preview.htmlPreview)}
            tabIndex={-1}
            title="Generated CV visual preview"
          />
        </div>
      ) : null}
    </SectionCard>
  )
}

export function buildPreviewDocument(htmlPreview: string) {
  const sanitizedPreview = sanitizeCvHtml(htmlPreview)
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src 'none'; connect-src 'none'; frame-src 'none'; form-action 'none'; base-uri 'none';"><meta name="referrer" content="no-referrer"><style>html{background:#fff;color:#191919;font:14px/1.5 Arial,sans-serif}body{margin:0;padding:32px}article{max-width:760px;margin:auto}h1{font-size:28px;margin:0 0 8px}h2{font-size:16px;margin:22px 0 6px;border-bottom:1px solid #bbb;padding-bottom:4px}p,ul{margin:6px 0}a{color:inherit;text-decoration:none}</style></head><body>${sanitizedPreview}</body></html>`
}
